### ISSUE TITLE
父类BaseResponseEntity有问题

### ISSUE THREAD

**Issue by shunHuang** [Mp5A5/HttpRequest#4]
Hi Man ~
当实体类去继承BaseResponseEntity时，要是实体类里服务端返回的结果也是叫data那就报
declares multiple JSON fields named data异常了，你为啥要在父类中声明这个 var data: T? = null ？

**Comment by Mp5A5** [comment]
你不用的bean 无需再写data直接解析data下的字段就行了，然后获取值的时候直接getData就行了

**Comment by Mp5A5** [comment]
比如我的
public class UploadEntity extends BaseResponseEntity<UploadEntity> {

    public List<FileBean> files;

    public class FileBean {
        public String fileName;
        public String url;
    }
}
假如这个类UploadEntity返回的就叫data，那么我直接泛型传入就行了

**Comment by Mp5A5** [comment]
我看看你的数据格式

**Comment by shunHuang** [comment]
我为了每个实体类不需要写code和message我封装了一个BaseBean：
public class BaseBean<T> extends BaseResponseEntity {

    @SerializedName("errorCode")
    private int code;

    @SerializedName("errorMsg")
    private String msg;

    public List<T> data;

    @Nullable
    @Override
    public String getMsg() {
        return msg;
    }

    @Override
    public void setMsg(String msg) {
        this.msg = msg;
    }
    ......
}

然后API这样写:
  @GET("wxarticle/chapters/json")
  Observable<BaseBean<JavaBean>> getList();

JavaBean是这样的:
public class JavaBean extends BaseBean {
    private int courseId;
    private int id;
    ......
}

**Comment by shunHuang** [comment]
我为了每个实体类不需要写code和message我封装了一个BaseBean：
public class BaseBean<T> extends BaseResponseEntity {

@SerializedName("errorCode")
private int code;

@SerializedName("errorMsg")
private String msg;

public List<T> data;

@Nullable
@Override
public String getMsg() {
    return msg;
}

@Override
public void setMsg(String msg) {
    this.msg = msg;
}
......
}

然后API这样写:
@get("wxarticle/chapters/json")
Observable<BaseBean<JavaBean>> getList();

JavaBean是这样的:
public class JavaBean  {
private int courseId;
private int id;
......
}

**Comment by shunHuang** [comment]
为啥我写了<T>这个github显示不了 (⊙﹏⊙)

**Comment by shunHuang** [comment]
为啥github的泛型显示不了 ？ (⊙﹏⊙)

**Comment by Mp5A5** [comment]
你加我微信
1732566826
